### ISSUE TITLE
type setという用語の使用方法について

### ISSUE THREAD

**Issue by nobishino** [kimuson13/tslist#12]
READMEに例えば次のような例があります:

```
/usr/local/go/src/fmt/print.go:62:15: 
Stringer
type set: empty
method list:
String() string
```

`fmt.Stringer`のunions部分はたしかにemptyなのですが、type setの仕様上の意味としては`fmt.Stringer`のtype setは「`String() string`を実装するすべての型からなる集合」となります。ですので、このような場合にtype set: emptyと表示するとmisleadingかもしれません。

https://go.dev/ref/spec#Interface_types

> The type set defined by such an interface is the set of types which implement all of those methods

ここで表したいものを表す用語がどれになるかは微妙なのですが、次のような記述もあるのでunionとかなら使えるかもしれません。

> Implementation restriction: A union (with more than one term) cannot contain the predeclared identifier comparable or interfaces that specify methods, or embed comparable or interfaces that specify methods.

**Comment by kimuson13** [comment]
issueありがとうございます！  
たしかにその通りだと思います！

empty type setは例として以下の`i`のような何も満たす型が存在しないinterfaceを指すような認識です。
```
type i interface {
    int
    string
}
```
なので、`fmt.Stringer`のようなメソッドリストだけ持っているinterfaceのtype set(この名前も誤解を生むかもしれないですが)は
`String() string`を満たすすべての型の集合になることから、`any`でもいいような気がしています。  
実装としても`any`として扱うようにしようと考えています。

追記: `go/x/exp/typeparams`の`NormalPerm`(interfaceの型セットをとれるもの)だと、上記のinterfaceのようなempty type setのものはエラーになるみたいです
